<?php

namespace App\Service;

use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class GroqPlaylistService
{
    public function __construct(private readonly HttpClientInterface $httpClient)
    {
    }

    /**
     * @param array<int, array{id:int,title:string,genre:string,artist:string,description:string}> $catalog
     * @return array{playlistName:string,songIds:array<int, int>,rationale:string}
     */
    public function generatePlaylist(string $prompt, array $catalog, int $count = 10): array
    {
        $apiKey = $_ENV['GROQ_API_KEY'] ?? $_SERVER['GROQ_API_KEY'] ?? '';
        $model = $_ENV['GROQ_MODEL'] ?? $_SERVER['GROQ_MODEL'] ?? 'llama-3.1-8b-instant';

        if (trim($apiKey) === '') {
            throw new \RuntimeException('GROQ_API_KEY is not configured.');
        }

        $count = max(3, min(20, $count));
        $catalog = array_slice($catalog, 0, 180);

        $catalogPayload = array_map(static function (array $song): array {
            return [
                'id' => (int) ($song['id'] ?? 0),
                'title' => (string) ($song['title'] ?? ''),
                'genre' => (string) ($song['genre'] ?? ''),
                'artist' => (string) ($song['artist'] ?? ''),
                'description' => (string) ($song['description'] ?? ''),
            ];
        }, $catalog);

        $instruction = [
            'task' => 'Generate a playlist from the provided catalog only.',
            'rules' => [
                'Select up to requested_count songs using only existing IDs from catalog.',
                'Never invent IDs or songs.',
                'Return strict JSON only, no markdown.',
            ],
            'expected_json' => [
                'playlist_name' => 'string',
                'song_ids' => ['int', 'int'],
                'rationale' => 'short string',
            ],
            'requested_count' => $count,
            'user_prompt' => $prompt,
            'catalog' => $catalogPayload,
        ];

        try {
            $response = $this->httpClient->request('POST', 'https://api.groq.com/openai/v1/chat/completions', [
                'headers' => [
                    'Authorization' => 'Bearer ' . $apiKey,
                    'Content-Type' => 'application/json',
                ],
                'json' => [
                    'model' => $model,
                    'temperature' => 0.4,
                    'messages' => [
                        [
                            'role' => 'system',
                            'content' => 'You are a music recommendation assistant. Always return valid JSON only.',
                        ],
                        [
                            'role' => 'user',
                            'content' => json_encode($instruction, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
                        ],
                    ],
                ],
                'timeout' => 30,
                'max_duration' => 45,
            ]);
        } catch (TransportExceptionInterface $e) {
            throw new \RuntimeException('Groq request failed: ' . $e->getMessage());
        }

        if ($response->getStatusCode() >= 400) {
            $detail = '';
            try {
                $payload = json_decode($response->getContent(false), true);
                $detail = $payload['error']['message'] ?? '';
            } catch (\Throwable) {
            }

            throw new \RuntimeException('Groq API error: HTTP ' . $response->getStatusCode() . ($detail !== '' ? (' - ' . $detail) : ''));
        }

        $payload = json_decode($response->getContent(false), true);
        $text = $payload['choices'][0]['message']['content'] ?? '';
        if (!is_string($text) || trim($text) === '') {
            throw new \RuntimeException('Groq returned empty content.');
        }

        $decoded = $this->decodeJsonResponse($text);
        $playlistName = trim((string) ($decoded['playlist_name'] ?? 'AI Playlist'));
        $rationale = trim((string) ($decoded['rationale'] ?? 'Generated by AI.'));
        $songIds = $decoded['song_ids'] ?? [];

        if (!is_array($songIds)) {
            $songIds = [];
        }

        $songIds = array_values(array_unique(array_map('intval', $songIds)));

        return [
            'playlistName' => $playlistName !== '' ? $playlistName : 'AI Playlist',
            'songIds' => $songIds,
            'rationale' => $rationale !== '' ? $rationale : 'Generated by AI.',
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function decodeJsonResponse(string $text): array
    {
        $trimmed = trim($text);
        $decoded = json_decode($trimmed, true);
        if (is_array($decoded)) {
            return $decoded;
        }

        if (preg_match('/\{[\s\S]*\}/', $trimmed, $matches) === 1) {
            $decoded = json_decode($matches[0], true);
            if (is_array($decoded)) {
                return $decoded;
            }
        }

        throw new \RuntimeException('Groq response is not valid JSON.');
    }
}
